### ISSUE TITLE
Using Secret Key on Mixer throws an exception with this library

### ISSUE THREAD

**Issue by cyberangel67** [SaviorXTanren/mixer-client-csharp#40] opened 2018-06-22 06:09 UTC
Seeing as the previous one was closed, even though I said it was still an issue I have created a new ticket.

Step 1)
Create an Application on Mixer using the Secret Key

Step 2)
Modify the sample Application to use Secret Key

Step 3)
Try to connect to Mixer and sign in.

It will throw an exception here, with a Bad Request exception.

        this.connection = await MixerConnection.ConnectViaShortCode(**clientID**, **secretKey**,
        new List<OAuthClientScopeEnum>()
        {
            OAuthClientScopeEnum.chat__chat,
            OAuthClientScopeEnum.chat__connect,
            OAuthClientScopeEnum.channel__details__self,
            OAuthClientScopeEnum.channel__update__self,
            OAuthClientScopeEnum.user__details__self,
            OAuthClientScopeEnum.user__log__self,
            OAuthClientScopeEnum.user__notification__self,
            OAuthClientScopeEnum.user__update__self,
        },
        (OAuthShortCodeModel code) =>
        {
            this.ShortCodeTextBox.Text = code.code;
            Process.Start("https://mixer.com/oauth/shortcode");
        });

**Comment by SaviorXTanren** [comment] 2018-06-22 06:18
Dude, just chill and give me 5 minutes to investigate this more before creating another issue, ok? I was in the process of already creating another before you created this.

Closing as a dupe of #41

**Closed by SaviorXTanren** 2018-06-22 06:18 UTC
